---
version: 2
updates:

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "actions/*"
    labels:
      - "bot"
    commit-message:
      prefix: "[CHORE](gha-deps)"
      include: "scope"
